matrix:
  include:
    # Unit Tests Node 8
    - language: node_js
      node_js: 8
      install:
      - yarn install
      script:
      - yarn test
      after_script:
      - 'cat coverage/lcov.info | ./node_modules/.bin/coveralls'
    
    # E2E Web
    - language: node_js
      node_js: 8.7
      services:
        - docker
      cache:
        yarn: true
        directories:
          - node_modules
      dist: trusty
      addons:
        apt:
          packages:
            # This is required to run new chrome on old trusty
            - libnss3
      env:
        - CI=false
        - NODE_VERSION="8.7"
      before_install:
      - docker run -d -p 9411:9411 openzipkin/zipkin
      - "export DISPLAY=:99.0"
      - "sh -e /etc/init.d/xvfb start"
      install:
      - yarn install
      - cd e2e-tests/react
      - yarn install
      before_script:
      - yarn run build
      - ./node_modules/.bin/serve -p 3000 -s build & SERVER_PID=$!
      script:
      - yarn test
      after_script:
      - kill -9 $SERVER_PID
