matrix:
  include:
    # Unit Tests Node 8
    - language: node_js
      env:
        - NAME='Unit Tests'
      node_js: 8
      install:
      - yarn install
      script:
      - yarn test
      after_script:
      - 'cat coverage/lcov.info | ./node_modules/.bin/coveralls'
    
    # E2E Web
    - services:
      - docker
      env:
        - CI=false
        - NODE_VERSION="8.7"
      install:
      - yarn install
      - cd e2e-tests/react
      - yarn install
      before_script:
      - yarn run build
      - docker run -d -p 9411:9411 openzipkin/zipkin
      - ./node_modules/.bin/serve -p 3000 -s build & SERVER_PID=$!
      script:
      - yarn test
      after_script:
      - kill -9 $SERVER_PID

    # Website
    - language: node_js
      env:
        - NAME='Website'
      node_js: 8
      script:
      - git config --global user.email "$GIT_USER@users.noreply.github.com"
      - git config --global user.name "Daniel Schmidt"
      - echo "machine github.com login $GIT_USER password $GITHUB_TOKEN" > ~/.netrc
      - npm install
      - cd website && npm install && GIT_USER=$GIT_USER npm run publish-gh-pages

